### POST request to create a new product
POST http://localhost:4000/products
Content-Type: application/json

{
    "name": "Customizable Dog Tag",
    "description": "Tag",
    "imageURL": "/assets/img/product9.png",
    "price": "9.99",
    "category": "Dog Tags",
    "stockQuantity": "20",
    "customizableFields": ["Name"]
  }

###