### POST request to create a new product
POST http://localhost:4000/products
Content-Type: application/json

{
    "name": "Customizable Dog Blanket",
    "description": "Blanket",
    "imageURL": "/assets/img/product8.jpg",
    "price": "35.99",
    "category": "Dog Blankets",
    "stockQuantity": "5",
    "customizableFields": ["Image"]
  }

###