### PUT request to update a product
PUT http://localhost:4000/products/423e4567-e89b-12d3-a456-426614174001
Content-Type: application/json

{
    "name": "Customizable Dog Toy",
    "description": "Personalized toy for your furry friend",
    "imageURL": "assets/img/product3.jpg",
    "price": "29.99",
    "category": "Dog Toys",
    "stockQuantity": "20",
    "customizableFields": []
  }

###