### POST request to create a new category
POST http://localhost:4000/orders
Content-Type: application/json

{
  "user": "123e4567-e89b-12d3-a456-426614174002",
  "orderDate": "2012-12-12",
  "totalAmount": "999.99"
}

###